### ISSUE TITLE
Invalid literal for int()

### ISSUE THREAD

**Issue by chandlercord** [cloud-compare/cloud-compare#1]
Wanna show me how to debug and fix?

[chandler:~/source/cloud-compare] master* ± pip list 2> /dev/null | grep jang
Django (1.9)
pep8 (1.7.0)

[chandler:~/source/cloud-compare] master* ± python -V
Python 2.7.13

[chandler:~/source/cloud-compare] master* 1 ± sqlite3 -version
3.8.0.2 2013-09-03 17:11:13 7dd4968f235d6e1ca9547cda9cf3bd570e1609ef

======================================================================
ERROR: test_aws (tests.test_scrape.ScrapeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/chandler/source/cloud-compare/tests/test_scrape.py", line 32, in test_aws
    call_command('ingest', self.tmpdir)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 119, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/Users/chandler/source/cloud-compare/pricing/management/commands/ingest.py", line 319, in handle
    ingestAmazon(directory, path2name(mjs['path']))
  File "/Users/chandler/source/cloud-compare/pricing/management/commands/ingest.py", line 172, in ingestAmazon
    ingest_AWS_offer(ojs, opath)
  File "/Users/chandler/source/cloud-compare/pricing/management/commands/ingest.py", line 135, in ingest_AWS_offer
    AWS.objects.bulk_create(updates)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 450, in bulk_create
    self._batched_insert(objs_without_pk, fields, batch_size)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 1056, in _batched_insert
    using=self.db)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 1039, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1063, in execute_sql
    for sql, params in self.as_sql():
  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1023, in as_sql
    for obj in self.query.objs
  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 962, in prepare_value
    value = field.get_db_prep_save(value, connection=self.connection)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 728, in get_db_prep_save
    prepared=False)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 720, in get_db_prep_value
    value = self.get_prep_value(value)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 1853, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: '0.645000000000000017763568394002504646778106689453125'

----------------------------------------------------------------------
Ran 5 tests in 739.898s

FAILED (errors=1)
Destroying test database for alias 'default'...

**Comment by chandlercord** [comment]
======================================================================
ERROR: test_aws (tests.test_scrape.ScrapeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/chandler/source/cloud-compare/tests/test_scrape.py", line 32, in test_aws
    call_command('ingest', self.tmpdir)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 119, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/Users/chandler/source/cloud-compare/pricing/management/commands/ingest.py", line 319, in handle
    ingestAmazon(directory, path2name(mjs['path']))
  File "/Users/chandler/source/cloud-compare/pricing/management/commands/ingest.py", line 172, in ingestAmazon
    ingest_AWS_offer(ojs, opath)
  File "/Users/chandler/source/cloud-compare/pricing/management/commands/ingest.py", line 135, in ingest_AWS_offer
    AWS.objects.bulk_create(updates)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 450, in bulk_create
    self._batched_insert(objs_without_pk, fields, batch_size)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 1056, in _batched_insert
    using=self.db)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 1039, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1063, in execute_sql
    for sql, params in self.as_sql():
  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1023, in as_sql
    for obj in self.query.objs
  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 962, in prepare_value
    value = field.get_db_prep_save(value, connection=self.connection)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 728, in get_db_prep_save
    prepared=False)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 720, in get_db_prep_value
    value = self.get_prep_value(value)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 1789, in get_prep_value
    return float(value)
ValueError: could not convert string to float:

----------------------------------------------------------------------
Ran 5 tests in 865.018s

FAILED (errors=1)
Destroying test database for alias 'default'...

**Comment by johnmuth81** [comment]
It looks like the Amazon field formats have changed a bit.
1) beginRange isn't aways an integer, although that may be a mistake on Amazon's end.
2) There are new entries where 'memory' is encoded as xx.xx GB instead of xx.xx Gib. Our  current translation messes this up.
